### ISSUE TITLE
Dev migrations vs Lift migrations

### ISSUE THREAD

**Issue by nikolasburk** [prisma/specs#122]
I'm observing the following migrations behaviour at the moment:

### `prisma2 dev`

When saving a change to the data model ...

- the database schema is being migrated to reflect the new data model.
- on the file system, a new migration is created inside `migrations/dev` directory. This migration is called `watch-TIMESTAMP`.
- in the database's `_Migration` table, a new record is added for this migration called `watch-TIMESTAMP`.

### `prisma2 lift save` and `prisma2 lift up`

After running these commands after a change to the data model ...

- the database schema is being migrated to reflect the new data model.
- on the file system, a new migration is created inside `migrations/` directory. This migration is called `TIMESTAMP-NAME`.
- the previous `migrations/dev` directory is deleted.
- in the database's `_Migration` table, a new record is added for this migration called `TIMESTAMP-NAME`.

### Questions

I'm wondering whether this is the expected behaviour, concretely:

- Should we create migration files for `prisma2 dev` migrations in `migrations/dev`?
- Should we store dev migrations in the `_Migrations` table?

What are the benefits and drawbacks of doing or not doing either of these things?

**Comment by janpio** [comment]
Very valid questions, that I also encountered when I spent the last few days understanding how Lift actually works to be able to update the Lift spec to reflect reality. 

I might be able to give you some answers on the current background:

Both of your questions come down to the fact that `prisma2 dev` or "Development Mode" is a different variant of migrations than what `prisma2 lift *` offers. 

The goal of Development Mode is to support quick iteration on the schema, being reflected in the database. This is helped by watchmode, but would also be able if what `dev` does after each change in regards to migrations, was available in a command (let's for now call it) `prisma2 lift foo`.

This command `prisma2 lift foo` that is run each time the watchmode of `dev` recognizes a schema change creates many small dev migrations in `migrations/dev` both in the filesystem and the `_Migrations` table. Only when you later run `prisma2 lift save` those are turned into a proper, named migration that can later be applied with `prisma2 lift up` on production.

So now to the questions:

> Should we create migration files for prisma2 dev migrations in migrations/dev?

Having the migrations in `migrations/dev` (and with a "name" `watch` instead of a manually supplied name) makes it possible for `save` to actually know that those are dev migrations that should be squashed.

> Should we store dev migrations in the _Migrations table?

That is indeed a question I also asked. But they have to, as otherwise there is no history of such a dev migration (so the smaller bit that will be later combined into a big thing) was executed on your development machine. 

So my next question obviously was if we can not just get rid of those _after_ we `save` (to squash them into 1 big migration) and apply that migration that replaces all the dev migrations: No we can not, as we _never_ want to mess with the migration history. Also when the big squashed migration is applied via `up` it probably/hopefully is a no-op - but we do not know (because who know who touched the database in the meantime).

---

There are additional possible problems around Development Mode of Lift like e.g. https://github.com/prisma/lift/issues/167
