### ISSUE TITLE
Spec out Destructive Changes Checking in Lift

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#169]
@tomhoule implemented the checking for destructive changes. The migration engine now returns a warning when data would be lost through a migration. 
Example: 
> You are about to drop the table `User`, which is not empty (11 rows).

I have created an [issue](https://github.com/prisma/lift/issues/146) that @timsuchanek should implement displaying those warnings in the CLI. After i created the issue i realized we don't have a spec for this behavior yet. Can you please spec this out? 🙏

**Comment by matthewmueller** [comment]
Let me know if you need anything else: https://github.com/prisma/specs/blob/lift/lift/Readme.md#prisma2-lift-up

**Comment by matthewmueller** [comment]
Continuing the discussion from this issue: https://github.com/prisma/lift/issues/146#issuecomment-536991485

I feel like we have 2 options in front of us for destructive changes.

1. Show this warning in the `lift save`, if the user doesn't want to do this, they can delete the migration manually
2. Show this warning in the `lift up` CLI and confirm the change

Both seem like bad options to me for any relatively large dataset. It could take minutes to see the CLI output for `lift save` or `lift up`. 

Since @mavilein said that in practice this hasn't been a problem for P1, I propose the following:

We **try** to show a warning on both `lift save` and `lift up`. We set a timeout for the queries to resolve and if we exceed the timeout's duration **and** we're deleting a model or field, then show the following warning:

⚠️You are about to drop the table User which may lead to data loss. 

If we're able to run the queries within the timeout duration, we show the following:

⚠️You are about to drop the table User, which is not empty (11 rows).

**Alternatives**

1. Run a simpler query: `SELECT * from User LIMIT 1`, this will tell us if we have data in there or not. We could then change from **may lead to data loss** to **will lead to data loss.** without getting specific.

Thoughts @mavilein?

**Comment by janpio** [comment]
Just to confirm: Is this information actually available in both for `save` and `up` @mavilein?

> We set a timeout for the queries to resolve and if we exceed the timeout's duration,

What queries exactly? I might be missing context here.

**Comment by matthewmueller** [comment]
> What queries exactly? I might be missing context here @matthewmueller

It's the SQL in the linked comment:

```sql
select count(name) from User where name is not null

```

**Comment by mavilein** [comment]
One clarifying comment that may not be obvious:
It's quite likely that you will run `lift save` against a different database than `lift up`. That means you might not get a warning in `lift save` on your box but on `lift up` in production or vice versa.

**Comment by mavilein** [comment]
The spec needs to answer the following questions:
1. How should the warnings be displayed and how does the user acknowledge the data loss?
2. Do we want to show those warnings in `lift save` as well?

**Comment by janpio** [comment]
After getting more explanation what this is about in backchannels:

I think that it probably should be implemented for both, `save` and `up`.

For both cases we have to decide individually if a "prompt" the user has to answer somehow is practical - or if an warning is enough. (Might differentiate if actual data is affected or not - although that feels like the super fancy version)
