### ISSUE TITLE
Spec needed: multi field unique API for Photon

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#170]
We started the [epic](https://github.com/prisma/prisma-engine/issues/28) for multi field unique in the engines now. We discovered that we need to spec how the GraphQL API and the corresponding DMMF representation looks like. We can't spec this out yet because we don't know yet how the API part in Photon will look like. This will probably have an influence on how we should design the query engine API.

**Comment by matthewmueller** [comment]
This is the current implementation in the photonJS spec:

https://github.com/prisma/specs/tree/master/photonjs#basic-queries

```js
// Find using composite/multi-field unique indexes
// Note: This example is not compatible with the example schema above.
const john: User | null = await photon.user.find({
  firstName: 'John',
  lastName: 'Doe',
})
```

This seems pretty reasonable to me, but we should definitely work towards a final photonJS spec.

**Comment by mavilein** [comment]
Should this give a compile error if the provided combination of fields is not unique? Or should it error when multiple unique criteria are provided, e.g. `id` and `email` is provided for a `User`.

**Comment by matthewmueller** [comment]
> Should this give a compile error if the provided combination of fields is not unique?

Good questions! My gut would be to suggest we follow how SQL handles queries in these cases, but I'll test it first to see how that feels.

**Comment by sorenbs** [comment]
I think the answer to @mavilein s question is yes and yes.

My understanding is that `find` should only allow lookups by a combination of fields that is guaranteed to be unique.

> In the following examples `id`, `email` and `[firstName, lastName]` is unique

This is not legal because firstName alone is not unique:

```
const john: User | null = await photon.user.find({
  firstName: 'John',
})
```

This is legal because the combination of firstName and lastName is unique:

```
const john: User | null = await photon.user.find({
  firstName: 'John',
  lastName: 'Doe',
})
```

> The following has not been specced before, but I believe we should handle it like this:

This is not legal because you could achieve a unique lookup by just using one of either `id` or `email`:

```
const john: User | null = await photon.user.find({
  id: '123',
  email: 'john@do.ee',
})
```

So the mental model here is that `find` is for retrieving a record by identity (some unique field combination.) If the intent is to retrieve the user with the id `123` but only if the email is also `john@do.ee`, then simply retrieve the user and check the email.

**Comment by matthewmueller** [comment]
This one is specced out here: https://github.com/prisma/specs/pull/179

Let me know if you have any questions/concerns about the implementation. We're waiting on @schickling  to look it over.
