### ISSUE TITLE
Prisma Core Primitive Types

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#177]
The schema spec contains various statements about core data types: https://github.com/prisma/specs/tree/master/schema#data-types

We need clarification on whether the current spec is final. We need this in order to start work on the related backend [epic](https://github.com/prisma/prisma-engine/issues/57).

**Comment by mavilein** [comment]
I am asking this because our current implementation in the parser diverges from the current state of the spec:
```
pub enum PrismaType {
    Int,
    Float,
    Decimal,
    Boolean,
    String,
    DateTime,
}
```

**Comment by tomhoule** [comment]
I am currently working on this issue (https://github.com/prisma/lift/issues/116), and it raises spec-level questions regarding the mapping of our core data types to MySQL types.

In short, we currently map prisma `String`s to  `varchar(191)` on MySQL, but understandably users want to have strings longer than 191 characters. The initial plan was to use `mediumtext` instead of `varchar(191)`, and work around the limitations of `text` fields. I can elaborate but I won't for the sake of brevity.

However there is a hard limitation we can't work around: foreign keys can never point to a `text` column.

Relevant MySQL docs page: https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html (`Index prefixes on foreign key columns are not supported. One consequence of this is that BLOB and TEXT columns cannot be included in a foreign key because indexes on those columns must always include a prefix length.`)

We discussed it with @marcus, and he suggested that we may need to map `String` to two column types in MySQL, `varchar(191)` for `String @id` columns, `mediumtext` for the others. This is tricky, but foreign keys are an important integrity mechanism. This relates to the question of core data types in that _one core prisma data type would map to two different types for some connectors, based on external factors_ (in this case, whether the column is part of the primary key).

@matthewmueller

**Comment by matthewmueller** [comment]
> However there is a hard limitation we can't work around: foreign keys can never point to a text column.

Thanks for raising this. I think this is a great example to chew on.

---

@mavilein do you have a mental model for when to add a core type and when to not? 

With this proposal it feels like we'll add core types we need them. Which could be fine, as long as were clear that's our strategy. My main concern with this approach is the following:

- Core types currently imply that we can implement them everywhere in some way. If we add a new core type, wouldn't we need to add that core type to all connectors?

Personally, I still think I'd prefer working with the types the database provides you. This way there's no misunderstanding about what type of data you're working with. 

```
datasource sqlite {
  provider = "sqlite"
}

type User@sqlite {
  id Int
  bio Text
  settings JSONB <- compile-time error
}
```

The pros to me are:

- It's a clear mental model to me: if you database supports it, we support it. 
- I don't think the learning curve is high because it's the same datatypes you've always been working with
- Generators will work fine, the connectors will map to internal core data types like String and Float

The cons to me are:

- Less approachable for newcomers to a schema
- The answer to what datatype I can use is that "it depends"
- Switch DBs is more explicitly painful (I think with core datatypes this will still be implicitly painful though)

**Comment by mavilein** [comment]
Re @matthewmueller:
> @mavilein do you have a mental model for when to add a core type and when to not?

If i needed to come up with a definition for core data types it would be something like this:
> The Prisma Core Data Types are a collection of a few common data types that can be provided by almost all databases. Either they are available natively in the database or they can be implemented with a reasonable shim. They enable the developer to reason about the programming representation in the application rather than database implementation details. If needed the user can take control over those implementation details with custom types.

The problem that i see with your proposal is the switching between databases. To my understanding we introduced SQLite to enable users to start with it locally and then easily switch to a different database subsequently. Your approach makes SQLite a close to useless connector as it supports only [very few data types](https://www.sqlite.org/datatype3.html). With your approach the SQLite connector would only support `Int`, `Float`, `Decimal` and `String`. It would not even have `Boolean`.
