### ISSUE TITLE
Error spec feedback

### ISSUE THREAD

**Issue by schickling** [prisma/specs#204]
- [x] **Most urgent**: Errors should be database agnostic (e.g. `P1000` assumes there are `database_host` and `database_user` which doesn't exist for SQLite, other example `P1003`) - related to [1]
- [x] Make error code first column in tables
- [x] Add type information to "Meta fields". Might be easiest to use TypeScript's type notation.
- [x] `P2006` type should be a meta field
- [x] Co-locate note with concrete error instead of listing them at the end of an error table. - related to [2]

## To discuss

- [x] Rethink error format (table, section, ...) [2]
  - [x] Add note/comment section per error
- [x] Globally vs locally defined error meta fields (see `Error Message Template Variables
`)
- [x] What is `Meta Schema Index` about?
- [x] Should errors be database agnostic or should there be database specific errors? [1]
- [ ] The line between the `different system components` seems not clear to me and might be confusing for the user as they are not aware of these implementation details. Can we come up with a more intuitive/clear separation? Do we need this separation?
- [x] Shouldn't `serialized_meta_schema` be pretty printed when logged?
- [x] How expensive is it to change errors end-to-end? Can we do things to make this easier in the future?

**Comment by divyenduz** [comment]
> Most urgent: Errors should be database agnostic (e.g. P1000 assumes there are database_host and database_user which doesn't exist for SQLite, other example P1003) - related to [1]

I think we need a notion of per datasource error message, as showing these fields makes sense for MySQL, Postgres but not SQLite, I will adjust it accordingly.

>  Add type information to "Meta fields". Might be easiest to use TypeScript's type notation.

Added that to the table (`Error Message Template Variables`) for now, I can use TS notation inline in the same table but that would mean every row has redundant `type Meta = { ... }`. Let me know if you see it better that way. 

## To discuss

> Rethink error format (table, section, ...) [2]
 >> Add note/comment section per error

I agree, this is still on my list but so far, couldn't find any better way to list errors than the table. Also spoke to Matt about it. I am using table with word wrap for now but I need to think more about it. 

>  Globally vs locally defined error meta fields (see `Error Message Template Variables`)

I don't fully follow. I wanted to write a one liner for all the template variables in this spec. Without thinking about global vs local. But thinking more about it, I think `Error Message Template Variables` should exist for SDK and Photon etc should have their local versions of it. Is that what you mean? 

>  What is `Meta Schema Index` about?

It is a one line description of meta schema variables (just to formally define them as just name + type might not be enough). This and `Error Message Template Variables` could have been merged as they are mostly similar with the only exception that for `Meta Schema Index` we might want to remove pretty printing from some fields. I can write them as I table assuming that it won't have the pretty printing as it is a Photon thing anyways, the schema should be an exclusive SDK thing. Does this make sense, if no, we can quickly chat about it. (`tl;dr` On my list). 

>  Should errors be database agnostic or should there be database specific errors? [1]

I think specific to database makes sense, we wouldn't want to not show `db_name` for MySQL because SQLite doesn't support that for example and with upcoming data sources like REST APIs etc, it makes more sense to have datasource specific error messages (built on top of a common base though)

>  The line between the `different system components` seems not clear to me and might be confusing for the user as they are not aware of these implementation details. Can we come up with a more intuitive/clear separation? Do we need this separation?

Can you please be more specific? Are you talking about stuff within the SDK like Lift, Introspection etc or something else? This represents the current understanding of the SDK and peripheral tools. This will need to be adjusted if our understanding of the SDK changes. Within the SDK, we expose (via marketing) things like Lift and Photon but maybe not schema parser. That can be discussed (we can for example refer to schema parser as a util function like we do for Prisma format)

>  Shouldn't `serialized_meta_schema` be pretty printed when logged?

I believe not automatically, it is for programmatic consumption. Pretty printing (right now) is a feature of Photon. If other consumers of the SDK want to color things they should consume the fields and do coloring on their own. If we want to expose coloring logic as well, that would need a separate spec. 

> How expensive is it to change errors end-to-end? Can we do things to make this easier in the future?

We have a place for new errors, we need to adjust the spec for new binaries (exposed through SDK) for example.

**Comment by divyenduz** [comment]
Closing this one, the last open item from this issue is tracked here: https://github.com/prisma/specs/issues/254
