### ISSUE TITLE
Consider renaming the join table's model to edge (or something else)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#264]
```diff
model Blog {
  id       Int       @id
  authors  Writer[]
}

model Writer {
  id      Int     @id
  blogs   Blog[]
}

// many to many
- model BlogsWriters {
+ edge BlogsWriters {
  blog      Blog
  author    Writer
  is_owner  Boolean
  @@unique([author, blog])
}
```

@nikolasburk brought up a good point yesterday that our thinking is too SQL specific where model = table. If you think about it as a graph, it's really just metadata attached to an edge. We could also do better validation if we have it be a different name.

**Comment by jasonkuhrt** [comment]
I would be 💯 💯 in favour of going toward graph thinking. Not because tables are bad but because they capture just a subset of data thinking. As a data company we should think broader. Seems to me all data in the universe is vastly intricately and perpetually connected. Apps merely make intensely simplified reflections of reality. Sometimes that's intentionally, but I think more often than not its indicative of primitive tools that we still work with. That's one way Prisma can come in to make a huge difference I think. Make it cheap to relate data in all manner of ways. Give users power to encode what would otherwise typically be implicit, thus brittle etc. 

I think this direction is a win:win where it becomes more intuitive for users but also more powerful.

**Comment by nikolasburk** [comment]
I really like this suggestion and I think we need another primitive in the Prisma schema to represent relations.

We should keep in mind that we're trying to optimize the tools for _application developers_, hence we should try to adopt their mindset when designing our tools.

As an application developer, I don't want to think about tables but I rather think about _application models_ and their _relationships_. In my mind, these are two different things:

- a model represents a concrete entity from my application domain
- a relationship represents connection between two models, and potentially some meta-information about that connection 

The only thing where I'm not too sure yet is the naming. I'm not sure we should start adopting graph terminology but I'd rather lean towards using vocabulary that feels very _natural_ to people. Ideally I'd just like to call this a `relation` block (IMO `model` and `relation` used together in that context feel very natural). But I'm not sure if this is a good idea seen that we already have an `@relation` attribute. On the other hand, it could also be positive that we have both a `relation` block as well as an `@relation` attribute since both are effectively used to provide meta-information to relations in the schema, so maybe that's not a bad thing...

**Comment by jasonkuhrt** [comment]
I like `relation` & `model` together too. I think `edge` would pair better with `node` than `model`. I _personally_ think `node` & `edge` are interesting but probably not enough to open a discussion on it (since it means renaming `model`). Rather, would just say not to mix the two groupings, each strong but mixing them being weaker than either (I think).

> But I'm not sure if this is a good idea seen that we already have an @relation attribute

Maybe the overlap is actually good if the concepts are inherently related, which they seem to be. Otherwise though IIUC @matthewmueller is investing an altogether differevent/revamped `@relation` system that might change it anyways?
