### ISSUE TITLE
Spec creating a secure HTTP endpoint with a auto-generated secret

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#283]
Based on 1) of https://github.com/prisma/prisma2/issues/782

**Comment by steebchen** [comment]
Why does this need to be secured? Isn't the query engine just run locally all the time anyway? Does this mean we need to implement HTTPS and additionally implement the "secret" thing?

Let's assume a user does want to run this publicly, why can they just not secure their servers themselves?

**Comment by pantharshit00** [comment]
> Why does this need to be secured? Isn't the query engine just run locally all the time anyway? Does this mean we need to implement HTTPS and additionally implement the "secret" thing?

> Let's assume a user does want to run this publicly, why can they just not secure their servers themselves?


Query engine runs on a random port every time. If that port is exposed, an attacker can wipe all of the data in the server(basically he as full data access) which in my opinion is a big security concern.


The secret would mean here a simple shared key between photon and query engine so that it is guaranteed that only photon can read data from the query engine. We can do it like we did in Prisma 1 where we used a jwt based authentication between client and server. In this case, we have the benefit of having both photon and query engine on same machine so this can be automatically generated with any user involvement.

**Comment by steebchen** [comment]
@pantharshit00 This is not true, since we bind the query engine to localhost (127.0.0.1). This means even if it runs on a random port it still runs on the loopback interface and thus can only be accessed locally.

**Comment by pantharshit00** [comment]
> This is not true, since we bind the query engine to localhost (127.0.0.1).

No, we don't. We bind to `0.0.0.0` which allows all IPv4 addresses to query the engine as seen in the below line of code from the engine

https://github.com/prisma/prisma-engine/blob/f784acd6a76f2e03974205313b6d219c04a91037/query-engine/prisma/src/main.rs#L125

**Comment by steebchen** [comment]
Well...

**Comment by steebchen** [comment]
see https://github.com/prisma/prisma-engine/issues/389

**Comment by divyenduz** [comment]
Internal note: dropping for this sprint
