### ISSUE TITLE
Errors - Decide for or against database-specific error messages

### ISSUE THREAD

**Issue by tomhoule** [prisma/specs#314]
In the current errors spec.

- Some error messages assume information that is not valid for all databases we support in their message, like [P1001: Database not reachable](https://github.com/prisma/specs/tree/master/errors#p1001-database-not-reachable), that contains `database_host` and `database_port`, which doesn't really apply to SQLite.
- The definition of [P1003: Database does not exist](https://github.com/prisma/specs/tree/master/errors#p1003-database-does-not-exist) suggests there is a different error message for SQLite and MySQL/Postgres.

Many of the other errors are the same across databases.

We should decide if it is ok to have a more than one message template for the same error (and the same error code), or if these should be separate errors.

Additionally, if we decide against this, and want to make one error code/type the same across databases, change to database-agnostic message variables, like `database_location: string` instead of both database_host and database_port, which doesn't apply to embedded databases for example.

**Comment by divyenduz** [comment]
Yes, we indeed want to have separate error messages backed by the same error code per database

- Same error code because fundamentally it is the same error
- Different error message because we want to show the best contextual error message per database (supporting multiple databases shouldn't jeopardize the quality of the error messages). We want to support a wide variety of databases in future (like excel etc) and this would help there. 

Please feel free to close this issue if you think that it is sufficiently answered

**Comment by tomhoule** [comment]
We implemented the infrastructure to make multiple error messages/metadata per error code possible today with @do4gr.
