### ISSUE TITLE
Prisma CLI: Introduce `prisma status` command

### ISSUE THREAD

**Issue by schickling** [prisma/specs#400]
## Context

The goal of Prisma (both as a company and as a technology) is to make databases easier to work with for application developers. In order to do that Prisma introduces abstraction layers and leverages complex techniques such as code generation and a set of language-agnostic binaries for the core of Prisma (which is written in Rust).

While Prisma unlocks a lot of value, this also opens the possibility for things to go wrong – either because of bugs (which we always want to fix in a timely manner) but also because of "wrong usage". Wrong usage in this case means a user might end up in a "bad state" by e.g. having forgotten to run a certain command or their DB schema has changed. While we strive to build resilient products (TODO provide link to design principles & philosophy), there are still cases we can't "automatically do the right thing for the user", so we have to provide the user with a way to see the "status" of Prisma.

## Proposal

As Prisma provides multiple interfaces (i.e. CLI, SDK, GUIs such as VSC and Studio ...) there are multiple different ways to surface this information, so in this issue I want to focus on how to surface the status information when using the CLI.

I'm proposing to introduce a new command to the Prisma CLI called `prisma status`. The command provides an overview of the status of Prisma which can contain information about the points below. It also serves as a good "home" for future (currently unknown) problems/inconsistencies we we should surface.

Here's an initial list of information/problems that the `prisma status` command could/should provide:

- Information about whether the Prisma schema and DB schema are "in sync" / compatible. If not maybe it shows some kind of "diff summary" and should also provide instructions/information on how to solve the problem. (Related: #394)
- Information about generators and the state of generated artifacts. For example the Prisma Client JS generator could implement a "status check" hook which when executed validates whether e.g. the binaries have been fetched correctly and whether the currently generated Client code (and types) are in sync with the Prisma schema.
- Check whether all different used Prisma tools have compatible versions
- _Other problems/points that should be brought to the users attention._

Note: This command is not quite the same but similar to the idea behind the `brew doctor` and `git status` command. Basically a command that you can run to "know what's going on" which builds trust and confidence for the user.

#### CLI Output

I'm not sure whether we should always print "all categories" of status checks incl. the successful checks or whether to just print the problematic checks.

#### Distinction between errors and warnings

It could make sense to distinguish between errors and warnings. Errors are something the user **has to** act on since they are blocked otherwise. Warnings are not critical to act on but recommended to fix.
We could for example also use this command to promote version upgrades.

## Next Steps

If we like the proposed idea above, we should proceed and write an initial spec for the `prisma status` command and get a minimal first version implemented.

**Comment by janpio** [comment]
Internal Note: Dropping until individual pieces of functionality are defined and implemented.

**Comment by mavilein** [comment]
Internal Note: Within the engine team we could start to prototype the functionality to check whether db and schema are in sync.

**Comment by JedWatson** [comment]
A few brief notes (haven't thought too deeply on this yet but it's something I'm really interested in)

* CLI is great but it would be very helpful if the tool is also available programatically, for higher-level node frameworks that are automating Prisma behind the scenes
* Ideally the status command would have knowledge of prisma migrate as well; so, being able to detect that a migration is available to be run, and ideally also know whether running that migration will bring the db and schema into sync
* Some conditions where the database and schema are out of sync, would be fairly predictable and safe to migrate (e.g add a column for a new field), while in other cases it's harder to know how to automatically do the right thing (e.g a destructive action). Also, reporting on "in-sync" vs "compatible" would be helpful.

There are (I think) three different states to consider:

1. The state my schema thinks it is in
2. The state I think my database is in
3. The state my database is actually in

This is a bit tricky because Prisma is designed to help in either direction; it can either update the schema by introspecting the database (I'll call this Mode A), or migrate the database based on the schema (I'll call this Mode B). Also there could be valid reasons for the database to be in a "known out of sync but compatible with schema" state. Maybe it would be useful for Prisma to support configuration explicitly controlling these modes; that would allow for more helpful instructions to be provided when there's a problem, on how to take the correct steps to fix it.

Looking outside the scope of this issue a bit, great DX would be:

* Ensure all migrations have been run and if not, offer to run them before reporting on status
* In Mode A, given an unexpected status, prompt to regenerate the schema by introspecting
* In Mode B, given an unexpected status, prompt to generate a migration
  * Report the actions to be taken by the migration and whether they're considered dangerous
  * Prompt to run the migration immediately then re-check status

For this to play well in a scenario where there's an intentional difference between the database and the schema, maybe there's a way to acknowledge (compatible) out-of-sync diffs and ignore them on future status reports / migration or schema generation.

Back to my "not just a CLI" point, there's an obvious way to imagine this as a CLI that a developer interacts with in their terminal; if you could imagine how to design a corresponding programmatic API so that other developers could build an interactive GUI on top of it (or automate it as part of a framework) that would be even better.

**Comment by JedWatson** [comment]
Something else to consider, say we had a higher level framework that generates Prisma schema and uses Migrate to manage the database. In that case, the status API would be a critical part of the puzzle in a scenario where:

A developer gets latest of a project, which includes changes to the schema with (either a migration or the requirement to generate a migration). The developer starts the project, and is prompted to apply the migration / otherwise perform actions to bring the database into a compatible state.

That's fairly straight-forward; now let's think about deployment scenarios. Say we're using pm2 to deploy the app to a cluster of processes.

When the new version is deployed (say via git), the app would perform the same validation but this time in a production scenario where there's no developer in a console ready to interact with the system. So the running of migrations needs to be automated and executed before the app boots up.

A complexity comes in here in terms of locking the migration. I've previously seen this managed by having a separate deployment and single process which is basically the migration worker; you deploy to that, once it's run, you deploy the new version of the app. It's a fairly robust concept, but makes deployment and production config more sophisticated. Heroku simplifies this with [release tasks](https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks) but it's still pretty advanced compared to how plug-and-play Prisma is otherwise.

I'm not sure there's anything Prisma can or should be doing to make this simpler, but wanted to call it out as a thing developers will really need to be aware of 🙂
