### ISSUE TITLE
Create high-level overview spec for current state of introspection engine

### ISSUE THREAD

**Issue by schickling** [prisma/specs#94]
Please also briefly outline how this is related to the migration engine ("symmetric mapping").

**Comment by mavilein** [comment]
Here is a high level view of the state of the introspection engine that we are working towards.
- The introspection engine is currently very thin. First it calls `.introspect()` on the `IntrospectionConnector` to get the calculated `DataModel` for the introspected database. This result is then passed to the Data Model library in order to print it.
- Currently there is only one connector for the introspection engine: the SQL introspection connector. This connector performs the work in two steps: At first it introspects a given database with the help of the `database-introspection` library to obtain a raw description of the Database Schema. This library is also used by SQL migration connector. Afterwards it calculates the Data Model for this Database Schema.
- This conversion is an inversion of what the SQL migration connector does: The SQL migration connector takes a Data Model and converts it into a Database Schema in order to caculate which migration steps need to be executed. The introspection connector does the inverse by taking a Database Schema and converting it into a Data Model.


<img width="771" alt="image" src="https://user-images.githubusercontent.com/2470881/63678915-79bcb700-c7f0-11e9-9ec4-76a23250473b.png">

**Comment by janpio** [comment]
@schickling How do you want to persist this information? Is there a follow up issue that will use this to build a fleshed out spec?

**Comment by schickling** [comment]
Thanks a lot for writing this up @mavilein. This will be taken into account by @matthewmueller's upcoming work on introspection + Prisma schema design.
